---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: helloworld-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: helloworld-dev
  chart:
    git: git@github.com:drweber/gitops-helm
    path: charts/helloworld
    ref: master
  values:
    containerPort: 8080
    image: gcr.io/net2phone-sandbox/hello:dev-8000
    replicaCount: 1
    hpa:
      enabled: false
