---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: helloworld-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:drweber/gitops-helm
    path: charts/helloworld
    ref: master
  values:
    containerPort: 8082
    image: gcr.io/net2phone-sandbox/hello:0.1
    replicaCount: 3
