apiVersion: v1
appVersion: "1.4.2u"
description: Podinfo Helm chart for Kubernetes
name: podinfo
version: 1.4.2
home: https://github.com/drweber/k8s-podinfo
sources:
- https://github.com/drweber/k8s-podinfo
maintainers:
  - name: drweber
    email: drweber@users.noreply.github.com
engine: gotpl
